# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - command: curl -sL https://raw.githubusercontent.com/twtwtw-gj/rewrite-git-user-data-bash/main/index.sh | bash
